### ISSUE TITLE
How Do You Compile This Makefile in Unix

### ISSUE THREAD

**Issue by vanleurth** [ionic-team/graphite#13]
I have been trying to install this in my server but it doesn't work.
I have tried to Make the file by typing Make. the Makefile runs and it gives me an error.
Is this the right way to build this project in my server?

Thank you

V.

**Comment by jwgmeligmeyling** [comment]
Whats the error you get? You should have python installed and added to your path I think..

Kind regards,

Jan-Willem

**Comment by vanleurth** [comment]
Hi Jan-Willem,

I guess I don’t know how to compile this source code.

I went to my UNIX server and at the root of the directory when I uploaded the contents of the zip file and typed; Make.

Then I got an error. But I’m not familiarized with compiling and making Python code.

Any help is appreciated,

Victor
