### ISSUE TITLE
Provide online "customize" generator

### ISSUE THREAD

**Issue by marceloverdijk** [ionic-team/graphite#2]
While thinking about the Graphite themes and customing it to use my own colors, it would be a nice idea to offer an online "customize" generator where an user can just provide &BASE_COLOR, &SECONDARY_COLOR, &HIGHLIGHT_COLOR (and later the JQM version) and generate the theme.
This would be similar like the customized download Twitter Bootstrap is providing.

What do you think?

**Comment by mlynch** [comment]
That was the initial idea, but due to time constraints we didn't implement it.

In that case, I obviously think it's an awesome idea :wink:

**Comment by marceloverdijk** [comment]
Good to hear :-)
