### ISSUE TITLE
Merge 8 themes under 1 css file as swatches

### ISSUE THREAD

**Issue by ghost** [ionic-team/graphite#9]
It's really hard to use themes from seperate css files.
Themes will be more and more useful like you can see bootstrap theme here:
https://github.com/commadelimited/jQuery-Mobile-Bootstrap-Theme
data-theme="a" -> aloe
data-theme="b" -> candy
data-theme="c" -> melon
data-theme="d" -> mint
data-theme="e" -> royal
data-theme="f" -> sand
data-theme="g" -> slate
data-theme="h" -> water

**Comment by mlynch** [comment]
Thanks for the issue notice.

I don't know if I want to do this. I think the swatch system is really confusing, and I want to have just one solid theme per app, with possible highlight swatches.

I think a better solution would be something like neue that we also developed here: https://github.com/driftyco/jqm-neue
